mail:
  smtp:
    port: 465
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
# admin 구글 계정
AdminMail:
  id: kyunghwanko1207@gmail.com
  password: osycbqxygjqrgrgy