spring:
  datasource:
    url: jdbc:mysql://database-1.cl4il8qu2fl3.us-east-1.rds.amazonaws.com:3306/beer_community?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/beer_community?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 9192631770m!
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1053412945892-im65lr8vu1dlsmjpdip3sh02130pc4it.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: u1ummtkDr_kylpyQhkz3
            client-secret: TKuY8hEIZ0
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 return해줌.(value에는 getAttributes()한 값들이 들어가있음)